Repository inspirezonetech/TeachMePythonLikeIm5, pull requests merged in 2020-11, with the labels that each got.

#71 Update README.md
  README.md
Labels: hacktoberfest-accepted

#64 Updated for-loop
  loops/for-loops.py
Labels: hacktoberfest-accepted

#70 Assignment operators
  operators/assigning.py
Labels: hacktoberfest-accepted, star :star2:

#65 Update List-declartion
  lists/declaring-lists.py
Labels: change required before merge!, hacktoberfest-accepted

#52 Created tutorial for Dictionary with challenge
  dictionaries/using-dictionaries-basic.py
Labels: hacktoberfest-accepted

#58 jbolanosc importing-modules python tutorial
  using-modules/calculator.py
  using-modules/creating-modules.py
  using-modules/importing-modules.py
Labels: hacktoberfest-accepted

#73 Added tutorial on advanced usage of dictionaries
  dictionaries/using-dictionaries-advanced.py
Labels: hacktoberfest-accepted
